config/routes.rb
RecommendationsApp::Application.routes.draw do

  root 'recommendations#index'

  get "/about" => 'pages#about'

  resources :recommendations

  # get "/recommendations" => 'recommendations#index'

  # get "/recommendations/new" => 'recommendations#new', :as => 'new_recommendation'
  # post "/recommendations" => 'recommendations#create'

  # get "/recommendations/:id" => 'recommendations#show', :as => "recommendation"
  # delete "/recommendations/:id" => 'recommendations#destroy'

  # get "/recommendations/:id/edit" => 'recommendations#edit', :as => 'edit_recommendation'
  # patch "/recommendations/:id" => 'recommendations#update'
end

app/models/item.rb
# The table is called "items"
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
before_filter :authenticate


  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['HTTP_USERNAME'] && password == ENV['HTTP_PASSWORD']
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  def update
    item = Item.find_by(id: params[:id])
    item.title = params[:title]
    item.description = params[:desc]
    item.free = params[:free]
    item.save

    redirect_to recommendations_url
  end
  def edit
    @item = Item.find_by(id: params[:id])
  end

  # Just present a blank form to the user
  # that they can fill in and submit.
  def new
  end

  # Receive submitted data and add a new item
  # into the database.
  def create
    i = Item.new
    i.title = params["title"]
    i.description = params["desc"]
    i.save
    redirect_to recommendations_url
  end

  def destroy
    item = Item.find_by(id: params[:id])
    # item.destroy
    redirect_to recommendations_url
  end

  def index

    @recommendations = Item.order(:title).page(params[:page]).per(2)

    # if params[:sort] != nil
    #if !params[:sort].nil?

    # SELECT * FROM ITEMS WHERE ID = 8
    # CREATE TABLE USERS (.........)
    # DROP TABLE USERS

    # SELECT * FROM ITEMS WHERE TITLE LIKE 'Apollo'; DROP TABLE USERS;

    # if params[:keyword].present?
    #   # @recommendations = Item.where("title LIKE ? OR description LIKE ?",
    #   #                               "%#{params[:keyword]}%",
    #   #                               "%#{params[:keyword]}%")

    #   @recommendations = Item.where("title LIKE :k OR description LIKE :k",
    #                                 :k => "%#{params[:keyword]}%")

    # elsif params[:sort].present?
    #   @recommendations = Item.order('title')
    # else
    #   @recommendations = Item.all
    # end
  end

  def show
    @item = Item.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecommendationsApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

</head>
<body>

  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Recommendations", recommendations_url, class: 'navbar-brand' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <form action="/recommendations" class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input name="keyword" type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/about">About</a></li>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

    <%= yield %>

  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About This App</h1>

<p>You recommend stuff and we take your money.</p>

app/views/recommendations/details.html.erb
<h1>Details</h1>

<h2>Title</h2>
<%= @item.title %>

<h2>Description</h2>
<%= @item.description %>

<p>
  <%= link_to "Go Back", root_url %>
</p>

app/views/recommendations/edit.html.erb
<div class="recommendation panel panel-success">
  <div class="panel-heading"><h1>Edit</h1>
  </div>

<%= form_tag(recommendation_url(@item.id), method: 'patch', class: 'form-horizontal description',role: 'form' ) do %>
  <div class = "form-group" >
    <label for="title" class="col-sm-2 control-label">Title:</label>
    <div class="col-sm-8">
      <input id="title" type="text" class="form-control" name="title" value="<%= @item.title %>">
    </div>
  </div>

  <div class="form-group">
    <label for="desc" class="col-sm-2 control-label">Description:</label>
    <div class="col-sm-8">

    <textarea class="form-control" id="desc" name="desc" rows="5" value="">
      <%= @item.description %>"
    </textarea>
    </div>
  </div>

  <div class = "form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <div class="checkbox">

          <label for="free">
           <input type="checkbox" id="free" name="free"> Free?
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Save!</button>
      </div>
    </div>


<% end %>

app/views/recommendations/index.html.erb
<p>
  <%= link_to "Add a New Item", new_recommendation_url %>
  | <%= link_to "Sort by Title", recommendations_url(:sort => "title") %>
  | Showing <%= @recommendations.count %> of <%= Item.count %> items.
</p>

<%= paginate @recommendations %>

  <% @recommendations.each do |r| %>
    <div class="recommendation row panel panel-success">
      <div class="panel-heading">
        <h1>
            <%= link_to r.title, recommendation_url(r.id) %>

          </h1>
        </div>
        <div class='description col-md-8'>

          <p><%= r.description %></p>
          <% if r.free? %>
              <%= image_tag 'free.jpg', class: 'free' %>
            <% end %>
          <p>
            <%= link_to "Delete", recommendation_url(r.id), method: 'delete' %>
            <%= link_to "Edit", edit_recommendation_url(r.id) %>
          </p>
        </div>
        <div class="col-md-4">
          <%= link_to image_tag(r.image_url), recommendation_url(r.id) %>
        </div>
    </div>
  <% end %>

app/views/recommendations/new.html.erb
<div class="recommendation panel panel-success">
  <div class="panel-heading"><h1>Add an Item</h1>
  </div>


<%= form_tag recommendations_url, method: 'post', class: 'form-horizontal description', role: 'form' do %>
  <div class = "form-group" >
    <%= label_tag "title", nil, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
       <%= text_field_tag  "title", nil, class: 'form-control' %>
      </div>
  </div>
  <div class = "form-group" >
    <%= label_tag "Description", nil, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
       <%= text_area_tag  "desc", nil, class: "form-control" %>
      </div>
</div>

<div class = "form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <div class="checkbox">
        <%= check_box_tag "free" %>
        <%= label_tag "free", "Free?" %>
      </div>
    </div>
  </div>

   <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Save!</button>
      </div>
    </div>

<% end %>
</div>

app/views/recommendations/show.html.erb
<h1>Item #<%= @item.id %></h1>

<p>
  <%= link_to "Go Back", recommendations_url %>
</p>
<div class="recommendation">
    <%= link_to image_tag(@item.image_url), recommendation_url(@item.id) %>
  <h1>
    <%= link_to @item.title, recommendation_url(@item.id) %>
      <% if @item.free? %>
        <%= image_tag 'free.jpg', class: 'free' %>
      <% end %>
  </h1>
  <p><%= @item.description %></p>
  <p>
    <%= link_to "Delete", recommendation_url(@item.id), method: 'delete' %>
    <%= link_to "Edit", edit_recommendation_url(@item.id) %>
  </p>
</div>